# Generated by Django 5.2.4 on 2025-08-01 13:19

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('block', models.CharField(blank=True, max_length=100, null=True)),
                ('location_panchayat', models.CharField(blank=True, max_length=100, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_time', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, tzinfo=datetime.timezone.utc))),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Agent', 'Agent'), ('Viewer', 'Viewer'), ('None', 'None')], default='Viewer', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('block', models.CharField(choices=[('Bochahan', 'Bochahan'), ('Minapur', 'Minapur'), ('Kanti', 'Kanti'), ('Mushahari', 'Mushahari'), ('Runisaidpur', 'Runisaidpur'), ('Other', 'Other')], max_length=100)),
                ('location_panchayat', models.CharField(max_length=100)),
                ('inquiry_source', models.CharField(choices=[('Advertisement', 'Advertisement'), ('Walk-in', 'Walk-in'), ('Online Form', 'Online Form'), ('Referral', 'Referral')], max_length=100)),
                ('student_class', models.CharField(choices=[('Play School', 'Play School'), ('Nursery', 'Nursery'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12')], max_length=30)),
                ('status', models.CharField(choices=[('Inquiry', 'Inquiry'), ('Registration', 'Registration'), ('Admission Test', 'Admission Test'), ('Admission Offered', 'Admission Offered'), ('Admission Confirmed', 'Admission Confirmed'), ('Rejected', 'Rejected')], default='Inquiry', max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('inquiry_date', models.DateField(blank=True, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('admission_test_date', models.DateField(blank=True, null=True)),
                ('admission_offered_date', models.DateField(blank=True, null=True)),
                ('admission_confirmed_date', models.DateField(blank=True, null=True)),
                ('rejected_date', models.DateField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('last_follow_up_updation', models.DateField(blank=True, null=True)),
                ('last_inquiry_updation', models.DateField(blank=True, null=True)),
                ('admin_assigned', models.ForeignKey(blank=True, default=None, limit_choices_to={'role': 'Admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_assigned', to=settings.AUTH_USER_MODEL)),
                ('assigned_agent', models.ForeignKey(blank=True, default=None, limit_choices_to={'role': 'Agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_agent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeadLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('previous_data', models.JSONField(default=dict)),
                ('new_data', models.JSONField(default=dict)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inquiries.lead')),
            ],
        ),
    ]
