# Generated by Django 5.2.4 on 2025-08-02 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='transfer_date',
            field=models.DateTimeField(blank=True, help_text='When the lead was transferred', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='transfer_reason',
            field=models.TextField(blank=True, help_text='Reason for transferring the lead', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='transferred_from',
            field=models.ForeignKey(blank=True, help_text='Agent who transferred this lead', limit_choices_to={'role': 'Agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='transferred_to',
            field=models.ForeignKey(blank=True, help_text='Agent who received this transferred lead', limit_choices_to={'role': 'Agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_leads', to=settings.AUTH_USER_MODEL),
        ),
    ]
