# Generated by Django 5.2.4 on 2025-08-02 10:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_lead_transfer_date_lead_transfer_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('lead_update', 'Lead Update'), ('lead_transfer', 'Lead Transfer'), ('call_made', 'Call Made'), ('lead_created', 'Lead Created'), ('lead_deleted', 'Lead Deleted'), ('login', 'Login'), ('logout', 'Logout'), ('export_data', 'Export Data'), ('other', 'Other')], max_length=20)),
                ('activity_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'Agent'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inquiries.lead')),
            ],
            options={
                'verbose_name_plural': 'Agent Activities',
                'ordering': ['-activity_time'],
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('call_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('call_duration', models.IntegerField(blank=True, help_text='Call duration in seconds', null=True)),
                ('call_status', models.CharField(choices=[('answered', 'Answered'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'Agent'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inquiries.lead')),
            ],
        ),
    ]
