# Generated by Django 5.2.4 on 2025-08-02 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_agentactivity_calllog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calllog',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='lead',
        ),
        migrations.CreateModel(
            name='CallRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_file', models.FileField(help_text='Upload call recording file', upload_to='call_recordings/')),
                ('duration', models.DurationField(blank=True, help_text='Duration of the call (automatically extracted)', null=True)),
                ('call_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when recording was uploaded')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the call', null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_recordings', to='inquiries.lead')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-call_date'],
            },
        ),
        migrations.DeleteModel(
            name='AgentActivity',
        ),
        migrations.DeleteModel(
            name='CallLog',
        ),
    ]
