# Generated by Django 5.2.4 on 2025-08-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0004_remove_calllog_agent_remove_calllog_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Inquiry', 'Inquiry'), ('Registration', 'Registration'), ('Admission Test', 'Admission Test'), ('Admission Offered', 'Admission Offered'), ('Admission Confirmed', 'Admission Confirmed'), ('Rejected', 'Rejected'), ('Viewer', 'Viewer')], default='Inquiry', max_length=100),
        ),
    ]
