# Generated by Django 5.2.4 on 2025-08-05 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0005_alter_lead_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('concerned_person', models.CharField(max_length=100)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('inquiry_source', models.CharField(choices=[('Advertisement', 'Advertisement'), ('Walk-in', 'Walk-in'), ('Online Form', 'Online Form'), ('Referral', 'Referral')], max_length=100)),
                ('status', models.CharField(choices=[('Inquiry', 'Inquiry'), ('Registration', 'Registration'), ('Admission Test', 'Admission Test'), ('Admission Offered', 'Admission Offered'), ('Admission Confirmed', 'Admission Confirmed'), ('Rejected', 'Rejected'), ('Viewer', 'Viewer')], default='Inquiry', max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('inquiry_date', models.DateField(blank=True, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('admission_test_date', models.DateField(blank=True, null=True)),
                ('admission_offered_date', models.DateField(blank=True, null=True)),
                ('admission_confirmed_date', models.DateField(blank=True, null=True)),
                ('rejected_date', models.DateField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('last_follow_up_updation', models.DateField(blank=True, null=True)),
                ('last_inquiry_updation', models.DateField(blank=True, null=True)),
                ('transfer_date', models.DateTimeField(blank=True, help_text='When the school lead was transferred', null=True)),
                ('transfer_reason', models.TextField(blank=True, help_text='Reason for transferring the school lead', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_assigned', models.ForeignKey(blank=True, default=None, limit_choices_to={'role': 'Admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_assigned_schools', to=settings.AUTH_USER_MODEL)),
                ('assigned_agent', models.ForeignKey(blank=True, default=None, limit_choices_to={'role': 'Agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_schools', to=settings.AUTH_USER_MODEL)),
                ('transferred_from', models.ForeignKey(blank=True, help_text='Agent who transferred this school lead', limit_choices_to={'role': 'Agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_schools', to=settings.AUTH_USER_MODEL)),
                ('transferred_to', models.ForeignKey(blank=True, help_text='Agent who received this transferred school lead', limit_choices_to={'role': 'Agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_schools', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
