# Generated by Django 5.2.4 on 2025-08-05 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0006_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolCallRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_file', models.FileField(help_text='Upload call recording file', upload_to='school_call_recordings/')),
                ('duration', models.DurationField(blank=True, help_text='Duration of the call (automatically extracted)', null=True)),
                ('call_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when recording was uploaded')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the call', null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_recordings', to='inquiries.school')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-call_date'],
            },
        ),
    ]
