# Generated by Django 5.2.4 on 2025-08-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0007_schoolcallrecording'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolcallrecording',
            name='school',
        ),
        migrations.RemoveField(
            model_name='schoolcallrecording',
            name='uploaded_by',
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('DNP', 'DNP'), ('Not interested', 'Not interested'), ('Interested', 'Interested'), ('Follow Up', 'Follow Up'), ('Low Budget', 'Low Budget'), ('Meeting', 'Meeting'), ('Proposal', 'Proposal')], default='Inquiry', max_length=100),
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='SchoolCallRecording',
        ),
    ]
