# Generated by Django 5.2.4 on 2025-08-22 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0009_school_lead_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='proposal_sent_by',
            field=models.ForeignKey(blank=True, help_text='User who sent the last proposal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='proposal_sent_date',
            field=models.DateTimeField(blank=True, help_text='When the last proposal was sent', null=True),
        ),
    ]
