# Generated by Django 5.2.4 on 2025-08-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0010_lead_proposal_sent_by_lead_proposal_sent_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Educational Institution', max_length=200)),
                ('address', models.TextField(default='Your Institution Address, City, State - PIN')),
                ('phone', models.CharField(default='+91-XXXXXXXXXX', max_length=20)),
                ('email', models.EmailField(default='info@yourinstitution.com', max_length=254)),
                ('website', models.URLField(default='www.yourinstitution.com')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Company Settings',
            },
        ),
    ]
