# Generated by Django 5.2.4 on 2025-10-04 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0011_companysettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='school',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='admission_confirmed_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='admission_offered_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='admission_test_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='block',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='location_panchayat',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='proposal_sent_by',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='proposal_sent_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='rejected_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='student_class',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='student_name',
        ),
        migrations.AddField(
            model_name='companysettings',
            name='gst_number',
            field=models.CharField(blank=True, help_text='GST Registration Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN Number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='tourism_license',
            field=models.CharField(blank=True, help_text='Tourism License Number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Customer's budget", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='customer_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='destination',
            field=models.CharField(default='To Be Determined', help_text='Preferred destination', max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='duration_days',
            field=models.IntegerField(blank=True, help_text='Trip duration in days', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='itinerary_sent_by',
            field=models.ForeignKey(blank=True, help_text='User who sent the last itinerary', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itineraries_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='itinerary_sent_date',
            field=models.DateTimeField(blank=True, help_text='When the last itinerary was sent', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='number_of_travelers',
            field=models.IntegerField(default=1, help_text='Number of people traveling (Pax)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='quoted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price quoted to customer', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='travel_end_date',
            field=models.DateField(blank=True, help_text='Preferred travel end date', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='travel_start_date',
            field=models.DateField(blank=True, help_text='Preferred travel start date', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='travel_type',
            field=models.CharField(choices=[('Honeymoon', 'Honeymoon'), ('Family', 'Family'), ('Solo', 'Solo'), ('Group', 'Group'), ('Corporate', 'Corporate'), ('Adventure', 'Adventure'), ('Pilgrimage', 'Pilgrimage'), ('Beach', 'Beach'), ('Hill Station', 'Hill Station')], default='Family', max_length=50),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='address',
            field=models.TextField(default='Your Company Address, City, State - PIN'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='email',
            field=models.EmailField(default='info@yourtravelcompany.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='name',
            field=models.CharField(default='Your Travel Company', max_length=200),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='website',
            field=models.URLField(default='www.yourtravelcompany.com'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='inquiry_source',
            field=models.CharField(choices=[('Website', 'Website'), ('Walk-in', 'Walk-in'), ('Social Media', 'Social Media'), ('Referral', 'Referral'), ('Advertisement', 'Advertisement'), ('Phone Call', 'Phone Call')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='mobile_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New Lead', 'New Lead'), ('DNP', 'DNP'), ('Not interested', 'Not interested'), ('Interested', 'Interested'), ('Follow Up', 'Follow Up'), ('Budget Discussion', 'Budget Discussion'), ('Itinerary Sent', 'Itinerary Sent'), ('Negotiation', 'Negotiation'), ('Booking Confirmed', 'Booking Confirmed'), ('Trip Completed', 'Trip Completed')], default='New Lead', max_length=100),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('star_rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], default=3)),
                ('amenities', models.TextField(blank=True, help_text='List amenities separated by commas', null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration_days', models.IntegerField(help_text='Number of days')),
                ('duration_nights', models.IntegerField(help_text='Number of nights')),
                ('destination', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryBuilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax', models.IntegerField(help_text='Number of travelers')),
                ('number_of_cabs', models.IntegerField(default=1)),
                ('duration_days', models.IntegerField()),
                ('base_price', models.DecimalField(decimal_places=2, default=0, help_text='Auto-calculated base price', max_digits=10)),
                ('markup_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Markup percentage on overall package', max_digits=5)),
                ('markup_amount', models.DecimalField(decimal_places=2, default=0, help_text='Markup amount', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, help_text='Final price with markup', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='inquiries.lead')),
                ('package', models.ForeignKey(help_text='Base package template', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inquiries.package')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('title', models.CharField(help_text="e.g., 'Port Blair Arrival'", max_length=200)),
                ('description', models.TextField()),
                ('cab_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ferry_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('speedboat_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('entry_tickets', models.DecimalField(decimal_places=2, default=0, help_text='Total entry ticket cost', max_digits=10)),
                ('activities', models.TextField(blank=True, help_text='Comma-separated list of activities', null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_days', to='inquiries.package')),
            ],
            options={
                'ordering': ['package', 'day_number'],
                'unique_together': {('package', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('Standard', 'Standard'), ('Deluxe', 'Deluxe'), ('Suite', 'Suite'), ('Presidential', 'Presidential'), ('Economy', 'Economy')], max_length=50)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_mattress_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_occupancy', models.IntegerField(default=2)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_categories', to='inquiries.hotel')),
            ],
            options={
                'ordering': ['hotel', 'price_per_night'],
                'unique_together': {('hotel', 'room_type')},
            },
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('number_of_rooms', models.IntegerField(default=1)),
                ('extra_mattress', models.IntegerField(default=0, help_text='Number of extra mattresses')),
                ('cab_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ferry_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('speedboat_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('entry_tickets', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('additional_charges', models.DecimalField(decimal_places=2, default=0, help_text='Any extra charges for this day', max_digits=10)),
                ('additional_charges_description', models.TextField(blank=True, null=True)),
                ('activities', models.TextField(blank=True, null=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inquiries.hotel')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='inquiries.itinerarybuilder')),
                ('room_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inquiries.roomcategory')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('itinerary', 'day_number')},
            },
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
