# Generated by Django 5.2.4 on 2025-10-06 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0013_customuser_is_active_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryday',
            name='check_in_date',
            field=models.DateField(blank=True, help_text='Hotel check-in date', null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='check_out_date',
            field=models.DateField(blank=True, help_text='Hotel check-out date', null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='is_hotel_booked',
            field=models.BooleanField(default=False, help_text='Mark as booked to block dates'),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='travel_date',
            field=models.DateField(blank=True, help_text='Actual travel date for this day', null=True),
        ),
        migrations.CreateModel(
            name='EventPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('event_type', models.CharField(help_text='e.g., Museum, Temple, Beach, Adventure Activity', max_length=100)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, help_text='Entry fee per person', max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('operating_hours', models.CharField(blank=True, help_text='e.g., 9 AM - 6 PM', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('number_of_rooms', models.IntegerField(default=1)),
                ('extra_mattress', models.IntegerField(default=0)),
                ('booking_status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('booking_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inquiries.hotel')),
                ('itinerary_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='inquiries.itineraryday')),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inquiries.roomcategory')),
            ],
            options={
                'ordering': ['check_in_date'],
                'unique_together': {('hotel', 'room_category', 'check_in_date', 'check_out_date')},
            },
        ),
    ]
